# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/Vsmart/V220A/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/Vsmart/

PRODUCT_COPY_FILES += \
    vendor/Vsmart/V220A/proprietary/apex/com.android.media.swcodec/lib64/libdirect-coredump.so:$(TARGET_COPY_OUT_SYSTEM)/apex/com.android.media.swcodec/lib64/libdirect-coredump.so \
    vendor/Vsmart/V220A/proprietary/lib/libcam.camadapter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.camadapter.so \
    vendor/Vsmart/V220A/proprietary/lib/libdirect-coredump.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdirect-coredump.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libcamera_client.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/libdirect-coredump.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libdirect-coredump.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/libeffectsconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libeffectsconfig.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/liblogwrap.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/liblogwrap.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/libnetd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libnetd_client.so \
    vendor/Vsmart/V220A/proprietary/lib/vndk-27/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vndk-27/libstdc++.so \
    vendor/Vsmart/V220A/proprietary/lib64/libdirect-coredump.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdirect-coredump.so \
    vendor/Vsmart/V220A/proprietary/lib64/vndk-27/libdirect-coredump.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libdirect-coredump.so \
    vendor/Vsmart/V220A/proprietary/lib64/vndk-27/libeffectsconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libeffectsconfig.so \
    vendor/Vsmart/V220A/proprietary/lib64/vndk-27/liblogwrap.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/liblogwrap.so \
    vendor/Vsmart/V220A/proprietary/lib64/vndk-27/libnetd_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libnetd_client.so \
    vendor/Vsmart/V220A/proprietary/lib64/vndk-27/libstdc++.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vndk-27/libstdc++.so
